version: "3.5"
services:
  fullstack-frontend:
    image: kp/fullstack-frontend
    build: .
    ports:
      - 8181:80
    networks:
      - fullstack-network
#  fullstack-frontend:
#    image: kp/fullstack-backend
#    build: .
#      - 8080
#    - fullstack-network
  fullstack-gateway:
    image: nginx:alpine
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/gateway.conf
    ports:
      - 8282:80
    networks:
      - fullstack-network
networks: 
  fullstack-network:
