spring:
  datasource:
    data:
    - "classpath:sql/h2-employee.sql"
  jpa:
    show-sql: true
# Need to enalbe SSL else HTTP2 would not work
server:
  http2:
    enabled: true
  servlet:
    context-path: /api
#  ssl:
#    key-store: classpath:keystore.store
#    key-store-password: secret